# Generated by Django 6.1 on 2026-08-25 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abv', models.DecimalField(decimal_places=2, help_text='Alcohol By Volume', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('distillery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spirits.distillery')),
            ],
        ),
    ]
